### ISSUE TITLE
Errore nella compilazione

### ISSUE THREAD

**Issue by davidelodde93** [Miaosi001/JW-Library-macOS#2]
Ho provato ad avviare tramite Xcode ma non parte, ho provato sia in modalità M1 che in modalità Rosetta 2

**Comment by Miaosi001** [comment]
Provato adesso, M1 con Xcode 13.0. Che errore ti dà?

**Comment by davidelodde93** [comment]
Se mi scrivi in privato via mail ti mando uno screenshot

**Comment by davidelodde93** [comment]
Il mio indirizzo è: Davide.lodde@gmail.com

**Comment by darioragusa** [comment]
Credo non ci sia più bisogno di compilare dato che è uscita l'app ufficiale
