### ISSUE TITLE
Edit *.jwpub files

### ISSUE THREAD

**Issue by livrasand** [Miaosi001/JW-Library-macOS#3]
Is it possible to reverse the function and embed your own edited content in the BLOB?

_Originally posted by @livrasand in https://github.com/darioragusa/JW-Library-macOS/issues/1#issuecomment-1129396877_

**Comment by livrasand** [comment]
I managed to edit the file but it shows me blank in JW Library, do you know what's going on? @darioragusa

**Comment by darioragusa** [comment]
I honestly don't know, I've never tried

**Comment by Godgethub** [comment]
Ciao Dario potresti aiutarmi in un progetto teocratico?
