### ISSUE TITLE
How can I install it on a mac?

### ISSUE THREAD

**Issue by livrasand** [Miaosi001/JW-Library-macOS#4]
How can I install on my mac? is there a package?

**Comment by darioragusa** [comment]
There's an old .app in the [releases](https://github.com/darioragusa/JW-Library-macOS/releases/tag/1.0.3) section or if you want the last version you can compile it by yourself

**Comment by livrasand** [comment]
Thank you very much friend, I hope it works for me, the circuit substitute has a Mac, but cannot install JW Library, apparently it is only for Mac with M1.
