### ISSUE TITLE
Encrypted content

### ISSUE THREAD

**Issue by temporarium** [Miaosi001/JW-Library-macOS#5]
@bedan1,

Just wondering if you know how the words are indexed in the SQLite db, especially in the `SearchIndexDocument` and `SearchTextRangeDocument` tables.

**Comment by darioragusa** [comment]
Hi @temporarium, are you looking for something like [this](https://github.com/darioragusa/JW-Library-macOS/issues/1#issuecomment-895946665)?

**Comment by temporarium** [comment]
I saw that before, but it's more cryptic than the original :-)

Have you confirmed that your deductions work?

Can you translate your graphic into some kind of algorithm?

**Comment by darioragusa** [comment]
I think it works(?), [here](https://github.com/darioragusa/JW-Library-macOS/issues/1#issuecomment-897657721) you can see it in action: it extract all the words in order and put them into a file. In my comment below there is a link to the script I used

**Comment by temporarium** [comment]
So, going backwards, given a sentence, how would you calculate the values for those index tables?

Example: "This is a test of a sample test sentence"
Easy enough to get an index of all the words used (and how often). But, how to get the values for _TextUnitIndices_, _PositionalList_ and _PositionalListIndex_ for each word?

EDIT: I think I've figured it out. Will implement a test.

**Comment by temporarium** [comment]
I give up :-(

**Comment by gokusander** [comment]
> OK. All sorted out. Not encrypted. Just using signed 8-bit hex.

How did you do that? I'm noob

**Comment by gokusander** [comment]
> So, going backwards, given a sentence, how would you calculate the values for those index tables?
> 
> Example: "This is a test of a sample test sentence" Easy enough to get an index of all the words used (and how often). But, how to get the values for _TextUnitIndices_, _PositionalList_ and _PositionalListIndex_ for each word?
> 
> EDIT: I think I've figured it out. Will implement a test.

want help? i trying implement a search in my jwpubs, how to get the values for TextUnitIndices, PositionalList and PositionalListIndex?
